### ISSUE TITLE
Credits for Arm-based GitHub Runners

### ISSUE THREAD

**Issue by benjyw** [WorksOnArm/GitHub-Runners#3]
If you are interested in requesting credits for Github Arm Runners, 
please fill out the details below.

Proposals will be evaluated on a biweekly basis and responses will be done via email

### Name, email, company, job title

Benjy Weinberger
benjyw@gmail.com

Stu Hood
stuhood@gmail.com

Josh Cannon
joshdcannon@gmail.com 

Lead maintainers of the Pants Build System.

Note that projects with two or more participants are preferred.

### Project Title and description

The Pants Build System

The Pants Build System

[Pants](https://www.pantsbuild.org/) is a modern build system with a strong focus on Python, as well as JVM, Go and other languages. It uses static analysis to infer dependencies automatically, instead of requiring large amounts of accompanying config and metadata. Pants is written in a combination of Rust and Python. It is distributed on [GitHub Releases](https://github.com/pantsbuild/pants/releases) as a set of per-platform native Python wheels with an embedded `.so` built from the Rust code.

Pants currently has around 20 active maintainers, across several companies and organizations, plus many more casual, occasional contributors.

Pants development is supported by Pants Build, a registered California 501c(6) non-profit (I am the treasurer of that organization).

### Describe your use case for these machines

As Linux on aarch64 becomes increasingly popular, more of our users are requesting that Pants run on this platform. To support this we need access to this platform to run CI to build, test and package Pants.

### Which members of the community would benefit from your work?

These fall into two broad categories:

- People who must run Pants in CI or desktop on Arm because they are building native code to deploy to Arm in production
- People running Pants on their CI or desktop Arm machines, even if their own code is not platform-specific

As Arm becomes more popular, these users have been increasing in number. We were previously using dedicated hardware generously provided by the "Works on Arm" program to build these binaries. But those resources are going away, and we need an alternative so we can continue to support our users on the Arm platform.

### Is the code that you’re going to run 100% open source? 

Yes.

Provide the URLs where it is located, or a Git repository.

Project code is here: https://github.com/pantsbuild/pants
Documentation is here: https://www.pantsbuild.org/

### Please outline your credits requirements at a high level to support Arm builds (purpose, duration, amount, other)

We need resources sufficient to run a GitHub Actions runner that can install the Rust toolchain, download third-party Rust and Python dependencies, compile Rust code, and run our platform-specific tests and smoke tests.  As a rough estimate, based on our resource consumption on the current "Works on Arm" machines: 8 cores, 32GB of RAM, 512GB SSD.

Please share a public URL of the CI dashboard (if applicable).

https://github.com/pantsbuild/pants/actions

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes, we own the logo and have already happily granted that use to Works on Arm.

## Important reminders and logistics

Approved projects will be encouraged to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

We are happy to already be doing so: https://github.com/pantsbuild/pants

Thanks for considering our project!

Approved projects are subject to a 90 day review process for termination.

In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by benjyw** [comment]
Hi, checking in on this - we are currently using a dedicated server generously provided by WOA, and we have been asked to stop using that server and request these resources instead. We hope to have a smooth transition that doesn't mean we cannot release for ARM. Thanks!

**Comment by shipra-ps** [comment]
Hi, Have sent you an email. Let's continue the discussion there.

**Comment by shipra-ps** [comment]
Closing this request as discussed over email.
