### ISSUE TITLE
Credits for Arm-based GitHub Runners: crystal-lang/crystal

### ISSUE THREAD

**Issue by beta-ziliani** [WorksOnArm/GitHub-Runners#5]
### Name, email, company, job title

Beta Ziliani, beta@manas.tech, Manas.Tech, Team Lead
Johannes Müller, johannes@manas.tech, Manas.Tech, Principal Engineer
Matías García, mgarcia@manas.tech, Manas.Tech, SRE

### Project Title and description

The Crystal Programming Language

Crystal is a programming language with the following goals:

 *   Have a syntax similar to Ruby (but compatibility with it is not a goal)
 *   Statically type-checked but without having to specify the type of variables or method arguments.
 *   Be able to call C code by writing bindings to it in Crystal.
 *   Have compile-time evaluation and generation of code, to avoid boilerplate code.
 *   Compile to efficient native code.

### Describe your use case for these machines

We note that we currently have a server from Equinix, but this is fading out and we think GH runners are more appropriate for our current usage.

Crystal [supports ARM64](https://crystal-lang.org/reference/1.13/syntax_and_semantics/platform_support.html#tier-2) in Tier 2 (likely soon to be Tier 1), and in order to do so we must test the compiler and stdlib tests in ARM machines.

### Which members of the community would benefit from your work?

Users and developers of Crystal that develops in ARM machines or build binaries for ARM servers.

### Is the code that you’re going to run 100% open source? 

It is, and it will always be: https://github.com/crystal-lang/crystal

### Please outline your credits requirements at a high level to support Arm builds (purpose, duration, amount, other)

According to [trunk.io](https://app.trunk.io/crystal-lang/crystal-lang/crystal/ci-analytics/1_5b896f0b-1609-4ed8-808b-8dbf941558c7?numericAggregateFunctions=NUMERIC_AGGREGATE_FUNCTION_SUM) we are currently using approximately 300hs per month.

Details can be found in: https://github.com/crystal-lang/crystal/actions/workflows/aarch64.yml

### Does the project allows the use of your project logo on ARM's developer website freely?

Yes.

## Important reminders and logistics

> Approved projects will be encouraged to provide credit back to Works on Arm
> in the form of a logo display, blog post, Twitter post, news release, or
> some other suitable acknowledgement.

In this regard, we note that we already link to WoA in our home page: https://crystal-lang.org/

**Comment by shipra-ps** [comment]
Thank you for your interest. We have sent you an email for further discussion. Mail failed to deliver to [johannes@manas.tech](mailto:johannes@manas.tech). Would request to loop the correct person in the email itself.

**Comment by shipra-ps** [comment]
Closing this as discussed over email.
