### ISSUE TITLE
Ultramarine Linux, Terra, Fyra Labs - Credits for Arm-based GitHub Runners

### ISSUE THREAD

**Issue by lleyton** [WorksOnArm/GitHub-Runners#7]
If you are interested in requesting credits for Github Arm Runners, 
please fill out the details below.

Proposals will be evaluated on a biweekly basis and responses will be done via email

### Name, email, company, job title

Lleyton Gray, [lleyton@fyralabs.com](mailto:lleyton@fyralabs.com), Fyra Labs, Founder/CEO

### Project Title and description

There are several projects we’re applying for, but they’re all related and support each other:

- Ultramarine Linux is a Fedora-based Linux distribution designed for ease-of-use, regardless of experience and use-case.

- Terra is a rolling-release community repository for Fedora containing a variety of software, with desktop users in mind.

- Ultramarine Anywhere is a project to bring Ultramarine (and Linux as a whole) to as many people as possible. We achieve this by working on hardware support for “non-traditional” platforms. Our current major focus is working alongside the Chrultrabook Project to allow Ultramarine to seamlessly run and function on Chromebook devices, with a growing focus on the ARM platform, which requires a lot more testing and rebuilding

- Fyra Labs software (all open-source) as a whole, as we'd like to offer ARM builds :p

### Describe your use case for these machines

We mainly want to use these machines as CI for aarch64 packages in Terra ARM. We're also using CI to build ARM images for Chromebooks and other devices.

### Which members of the community would benefit from your work?

Everyone who uses Ultramarine Linux on ARM. This would also benefit the users of Terra, which are spread across the Fedora ecosystem, outside of just Ultramarine. Additionally, our work on hardware support would be able to benefit those who are on the platforms we’re developing for, across the Linux ecosystem.

### Is the code that you’re going to run 100% open source? 

Yes, all of the code we're using is open source. However, certain packages in Terra may be for 3rd party proprietary software, for example, we provide a package for Discord desktop.

https://github.com/terrapkg/packages
https://github.com/ultramarine-linux/ (the entire org is relevant)
https://github.com/FyraLabs/kaibutsu (our patches and build system for kernel development and testing)
https://github.com/ellyq/linux (development tree for mt8183 kernel patches, from the chultrabook project, used in Ultramarine)

### Please outline your credits requirements at a high level to support Arm builds (purpose, duration, amount, other)

Before this, we were using an Ampere Altra Equinix Metal server sponsored by WoA with ~160 cores and ~500 GB of memory. Ideally, we'd be able to match this.

Please share a public URL of the CI dashboard (if applicable).

CI runs can be viewed at the /actions page of each repo.

### Does the project allows the use of your project logo on ARM's developer website freely? Yes / No / Not Sure

Yes

## Important reminders and logistics

Approved projects will be encouraged to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by shipra-ps** [comment]
Thankyou for your interest. We have sent you an email for further discussion.

**Comment by shipra-ps** [comment]
Closing the ticket as needful has been done.
